module.exports = {
    purge: {
        content: ['./src/**/*.{js,jsx,ts,tsx}', './public/index.html'],
        safelist: [
            'bg-gray-100',
            'bg-red-100',
            'bg-yellow-100',
            'bg-green-100',
            'bg-blue-100',
            'bg-indigo-100',
            'bg-purple-100',
            'bg-pink-100',
            'bg-gray-500',
            'bg-red-500',
            'bg-yellow-500',
            'bg-green-500',
            'bg-blue-500',
            'bg-indigo-500',
            'bg-purple-500',
            'bg-pink-500',
            'bg-gray-400',
            'bg-red-400',
            'bg-yellow-400',
            'bg-green-400',
            'bg-blue-400',
            'bg-indigo-400',
            'bg-purple-400',
            'bg-pink-400',
            'bg-gray-200',
            'bg-red-200',
            'bg-yellow-200',
            'bg-green-200',
            'bg-blue-200',
            'bg-indigo-200',
            'bg-purple-200',
            'bg-pink-200',
            'bg-gray-600',
            'bg-red-600',
            'bg-yellow-600',
            'bg-green-600',
            'bg-blue-600',
            'bg-indigo-600',
            'bg-purple-600',
            'bg-pink-600',
            'text-gray-500',
            'text-red-500',
            'text-yellow-500',
            'text-green-500',
            'text-blue-500',
            'text-indigo-500',
            'text-purple-500',
            'text-pink-500',
            'text-gray-800',
            'text-red-800',
            'text-yellow-800',
            'text-green-800',
            'text-blue-800',
            'text-indigo-800',
            'text-purple-800',
            'text-pink-800',
            'left-5',
            'right-5',
            'ring-gray-300',
            'ring-red-300',
            'ring-yellow-300',
            'ring-green-300',
            'ring-blue-300',
            'ring-indigo-300',
            'ring-purple-300',
            'ring-pink-300',
        ],
    },
    darkMode: false, // or 'media' or 'class'
    theme: {
        extend: {
            colors: {
                transparent: 'transparent',
                current: 'currentColor',
            },
        },
    },
    variants: {
        extend: {},
    },
    plugins: [require('@tailwindcss/forms')],
};
